server:
  port: ${MEMBERS_SERVICE_PORT}

spring:
  config:
    activate:
      on-profile: prod

    # yml 설정
    import:
      - classpath:/product/application-members-prod.yml
      - classpath:/product/application-orders-prod.yml
      - classpath:/product/application-review-prod.yml
      - classpath:/product/application-wish-prod.yml

  # db 설정 - ddl, sql, dialect 설정
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB106Dialect
  # db 설정 - 스키마 연결
  datasource:
    url: ${MASTER_DB_URL}
    username: ${MASTER_DB_USERNAME}
    password: ${MASTER_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


# JWT 설정
JWT:
  secret-key: ${JWT_SECRET_KEY}
  header: Authorization
  prefix: Bearer
  token:
    access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}