spring:
  # 메일 기능 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_MEMBERSNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true                        # SMTP 서버에 인증 필요한 경우 true로 지정한다. Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정해야 한다.
          starttls: # SMTP 서버에 TLS를 사용할 것인지 여부를 지정한다. Gmail SMTP 서버는 TLS를 사용해야 하기 때문에 true로 설정해야 한다.
            enable: true

      auth-code-expiration-millis: ${EMAIL_AUTH_CODE_EXPIRATION_MILLIS}

  # Redis 설정
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
    web:
      pageable:
        one-indexed-parameters: true